# Generated by Django 5.0.2 on 2024-03-18 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_upload_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='name',
            field=models.CharField(default='Empty', max_length=255),
        ),
        migrations.AddField(
            model_name='upload',
            name='rejected',
            field=models.BooleanField(default=False),
        ),
    ]
