# Generated by Django 5.0.2 on 2024-05-19 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_upload_name_upload_rejected'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='viewers',
            field=models.IntegerField(default=0),
        ),
    ]
