# Generated by Django 5.0.3 on 2024-05-03 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_gamification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamification',
            name='update_frequency_points',
        ),
    ]
