# Generated by Django 5.0.3 on 2024-05-03 14:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_remove_gamification_update_frequency_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamification',
            name='age_points',
            field=models.IntegerField(default=1, verbose_name='Age Points'),
        ),
        migrations.AlterField(
            model_name='gamification',
            name='points',
            field=models.IntegerField(default=10, validators=[django.core.validators.MaxValueValidator(100)], verbose_name='Points'),
        ),
    ]
