# Generated by Django 5.0.3 on 2024-05-03 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_gamification_age_points_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamification',
            name='total_ads_count',
            field=models.IntegerField(default=0, verbose_name='Total Ads'),
        ),
    ]
