# Generated by Django 5.0.3 on 2024-06-11 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_upload_viewers'),
        ('user', '0007_gamification_total_ads_count'),
    ]

    operations = [
    ]
